### NumPy Basics

In [1]:
# importing numpy
import numpy as np

##### Creating Arrays

In [3]:
# add a list
np.array([0,1,2,3,4,5,6,7,8,9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# initialize ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# initialize zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# initialize random numbers
np.random.random(10)

array([0.61306764, 0.43164544, 0.6334958 , 0.49397106, 0.09243124,
       0.57973873, 0.48743213, 0.06767047, 0.42601021, 0.64346797])

#### Array Arithmetic

In [7]:
# plus 
np_data = np.array([0,1,2,3,4,5,6,7,8,9])
np_ones = np.ones(10)
np_data + np_ones

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
# minus 
np_data = np.array([0,1,2,3,4,5,6,7,8,9])
np_ones = np.ones(10)
np_data - np_ones

array([-1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [9]:
# multiply by two 
np_data = np.array([0,1,2,3,4,5,6,7,8,9])
np_ones = np.ones(10)
np_data * (np_ones+1)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [10]:
# divide by 2
np_data = np.array([0,1,2,3,4,5,6,7,8,9])
np_ones = np.ones(10)
np_data / (np_ones+1)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [11]:
# broadcast multiplication
np_data = np.array([0,1,2,3,4,5,6,7,8,9])
np_data * 1.5

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5])

#### Aggregation

In [12]:
# min
np_data = np.array([0,1,2,3,4,5,6,7,8,9,10])
np_data.min()

0

In [13]:
# max
np_data = np.array([0,1,2,3,4,5,6,7,8,9,10])
np_data.max()

10

In [14]:
# sum
np_data = np.array([0,1,2,3,4,5,6,7,8,9,10])
np_data.sum()

55

In [15]:
# mean
np_data = np.array([0,1,2,3,4,5,6,7,8,9,10])
np_data.mean()

5.0

In [16]:
# standard deviation
np_data = np.array([0,1,2,3,4,5,6,7,8,9,10])
np_data.std()

3.1622776601683795

#### Arrays with more Dimensions

In [21]:
# create zero, one and random 3x2 matrices
zero_nd = np.zeros((3,2))
one_nd = np.ones((3,2))
random_nd = np.random.random((3,2))
print(f'zero 3x2\n{zero_nd}\n\none 3x2\n{one_nd}\n\nrandom 3x2\n{random_nd}')

zero 3x2
[[0. 0.]
 [0. 0.]
 [0. 0.]]

one 3x2
[[1. 1.]
 [1. 1.]
 [1. 1.]]

random 3x2
[[0.15941314 0.48724027]
 [0.95799156 0.7217771 ]
 [0.38127813 0.77514596]]


#### Matrix Arithmetic

In [8]:
# add ones to 3x2 data
data = np.array([[1,2],[3,4],[5,6]])
one_nd = np.ones((3,2))
data + one_nd

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

#### Dot Product

In [4]:
# 1x3 multiplied by 3x2 equals 1x2
data = np.array([1,2,3])
powers_of_ten = np.array([[1,10], [100,1000], [10000,100000]])
data.dot(powers_of_ten)

array([ 30201, 302010])

In [ ]:
# longer approach but similar to above 


#### Matrix Aggregation

In [8]:
# min
np_data = np.array([[0,1], [2,3] ,[4,5], [6,7], [8,9]])
print(f'original data - 5x2\n{np_data}\n')
print(f'min of data - 1x1\n{np_data.min()}\n')
print(f'min of columns - 1x2\n{np_data.min(axis=0)}\n')
print(f'min of rows - 1x5\n{np_data.min(axis=1)}')


original data - 5x2
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

min of data - 1x1
0

min of columns - 1x2
[0 1]

min of rows - 1x5
[0 2 4 6 8]


In [9]:
# max
np_data = np.array([[0,1], [2,3] ,[4,5], [6,7], [8,9]])
print(f'original data - 5x2\n{np_data}\n')
print(f'max of data - 1x1\n{np_data.max()}\n')
print(f'max of columns - 1x2\n{np_data.max(axis=0)}\n')
print(f'max of rows - 1x5\n{np_data.max(axis=1)}')



original data - 5x2
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

max of data - 1x1
9

max of columns - 1x2
[8 9]

max of rows - 1x5
[1 3 5 7 9]


In [10]:
# sum
np_data = np.array([[0,1], [2,3] ,[4,5], [6,7], [8,9]])
print(f'original data - 5x2\n{np_data}\n')
print(f'sum of data - 1x1\n{np_data.sum()}\n')
print(f'sum of columns - 1x2\n{np_data.sum(axis=0)}\n')
print(f'sum of rows - 1x5\n{np_data.sum(axis=1)}')



original data - 5x2
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

sum of data - 1x1
45

sum of columns - 1x2
[20 25]

sum of rows - 1x5
[ 1  5  9 13 17]


In [12]:
# mean
np_data = np.array([[0,1], [2,3] ,[4,5], [6,7], [8,9]])
print(f'original data - 5x2\n{np_data}\n')
print(f'mean of data - 1x1\n{np_data.mean()}\n')
print(f'mean of columns - 1x2\n{np_data.mean(axis=0)}\n')
print(f'mean of rows - 1x5\n{np_data.mean(axis=1)}')


original data - 5x2
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

mean of data - 1x1
4.5

mean of columns - 1x2
[4. 5.]

mean of rows - 1x5
[0.5 2.5 4.5 6.5 8.5]


In [13]:
# std
np_data = np.array([[0,1], [2,3] ,[4,5], [6,7], [8,9]])
print(f'original data - 5x2\n{np_data}\n')
print(f'std of data - 1x1\n{np_data.std()}\n')
print(f'std of columns - 1x2\n{np_data.std(axis=0)}\n')
print(f'std of rows - 1x5\n{np_data.std(axis=1)}')


original data - 5x2
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

std of data - 1x1
2.8722813232690143

std of columns - 1x2
[2.82842712 2.82842712]

std of rows - 1x5
[0.5 0.5 0.5 0.5 0.5]


#### Transposing and Reshaping

In [2]:
# transpose 5x2 to 2x5
np_data = np.array([[0,1], [2,3] ,[4,5], [6,7], [8,9]])
print(f'Original data - 5x2\n{np_data}\n')
print(f'Transposed data - 2x5\n{np_data.T}\n')

Original data - 5x2
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Transposed data - 2x5
[[0 2 4 6 8]
 [1 3 5 7 9]]



In [7]:
# reshape 1x10 to 2x5 and 5x2
np_data = np.array([0,1,2,3,4,5,6,7,8,9])
print(f'Original data - 1x10\n{np_data}\n')
print(f'Reshaped data - 2x5\n{np_data.reshape(2,5)}\n')
print(f'Reshaped data - 5x2\n{np_data.reshape(5,2)}\n')

Original data - 1x10
[0 1 2 3 4 5 6 7 8 9]

Reshaped data - 2x5
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped data - 5x2
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]



#### More Dimensions

In [3]:
# 4x3x2 dimension of ones
np_data = np.ones((4,3,2))
print(f'4x3x2 dimension of ones \n\n{np_data}')

4x3x2 dimension of ones 

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


# 