### NumPy Basics

In [1]:
# importing numpy
import numpy as np

##### Creating Arrays

In [3]:
# add a list
np.array([0,1,2,3,4,5,6,7,8,9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# initialize ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# initialize zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# initialize random numbers
np.random.random(10)

array([0.61306764, 0.43164544, 0.6334958 , 0.49397106, 0.09243124,
       0.57973873, 0.48743213, 0.06767047, 0.42601021, 0.64346797])

#### Array Arithmetic

In [7]:
# plus 
np_data = np.array([0,1,2,3,4,5,6,7,8,9])
np_ones = np.ones(10)
np_data + np_ones

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
# minus 
np_data = np.array([0,1,2,3,4,5,6,7,8,9])
np_ones = np.ones(10)
np_data - np_ones

array([-1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [9]:
# multiply by two 
np_data = np.array([0,1,2,3,4,5,6,7,8,9])
np_ones = np.ones(10)
np_data * (np_ones+1)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [10]:
# divide by 2
np_data = np.array([0,1,2,3,4,5,6,7,8,9])
np_ones = np.ones(10)
np_data / (np_ones+1)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [11]:
# broadcast multiplication
np_data = np.array([0,1,2,3,4,5,6,7,8,9])
np_data * 1.5

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5])

#### Aggregation

In [12]:
# min
np_data = np.array([0,1,2,3,4,5,6,7,8,9,10])
np_data.min()

0

In [13]:
# max
np_data = np.array([0,1,2,3,4,5,6,7,8,9,10])
np_data.max()

10

In [14]:
# sum
np_data = np.array([0,1,2,3,4,5,6,7,8,9,10])
np_data.sum()

55

In [15]:
# mean
np_data = np.array([0,1,2,3,4,5,6,7,8,9,10])
np_data.mean()

5.0

In [16]:
# standard deviation
np_data = np.array([0,1,2,3,4,5,6,7,8,9,10])
np_data.std()

3.1622776601683795

#### Arrays with more Dimensions

In [21]:
# create zero, one and random 3x2 matrices
zero_nd = np.zeros((3,2))
one_nd = np.ones((3,2))
random_nd = np.random.random((3,2))
print(f'zero 3x2\n{zero_nd}\n\none 3x2\n{one_nd}\n\nrandom 3x2\n{random_nd}')

zero 3x2
[[0. 0.]
 [0. 0.]
 [0. 0.]]

one 3x2
[[1. 1.]
 [1. 1.]
 [1. 1.]]

random 3x2
[[0.15941314 0.48724027]
 [0.95799156 0.7217771 ]
 [0.38127813 0.77514596]]


#### Matrix Arithmetic

In [8]:
# add ones to 3x2 data
data = np.array([[1,2],[3,4],[5,6]])
one_nd = np.ones((3,2))
data + one_nd

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

# 