### NumPy Basics

In [1]:
# importing numpy
import numpy as np

##### Creating Arrays

In [6]:
# add a list
np.array([0,1,2,3,4,5,6,7,8,9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# initialize ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
# initialize zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
# initialize random numbers
np.random.random(10)

array([0.57342924, 0.43406465, 0.59211436, 0.3759747 , 0.60462641,
       0.76794533, 0.32663271, 0.7597919 , 0.64582279, 0.65307835])

#### Array Arithmetic

In [12]:
# plus 
np_data = np.array([0,1,2,3,4,5,6,7,8,9])
np_ones = np.ones(10)
np_data + np_ones

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
# minus 
np_data = np.array([0,1,2,3,4,5,6,7,8,9])
np_ones = np.ones(10)
np_data - np_ones

array([-1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [17]:
# multiply by two 
np_data = np.array([0,1,2,3,4,5,6,7,8,9])
np_ones = np.ones(10)
np_data * (np_ones+1)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [18]:
# divide by 2
np_data = np.array([0,1,2,3,4,5,6,7,8,9])
np_ones = np.ones(10)
np_data / (np_ones+1)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [19]:
# broadcast multiplication
np_data = np.array([0,1,2,3,4,5,6,7,8,9])
np_data * 1.5

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5])

#### Aggregation

In [27]:
# min
np_data = np.array([0,1,2,3,4,5,6,7,8,9,10])
np_data.min()

0

In [28]:
# max
np_data = np.array([0,1,2,3,4,5,6,7,8,9,10])
np_data.max()

10

In [29]:
# sum
np_data = np.array([0,1,2,3,4,5,6,7,8,9,10])
np_data.sum()

55

In [30]:
# mean
np_data = np.array([0,1,2,3,4,5,6,7,8,9,10])
np_data.mean()

5.0

In [31]:
# standard deviation
np_data = np.array([0,1,2,3,4,5,6,7,8,9,10])
np_data.std()

3.1622776601683795

# 